---
# tasks file for homelab-container-registry
- name: Create directory for certs
  ansible.builtin.file:
    path: "/certs"
    state: directory
    mode: 0755

- name: Copy Certificate Over
  ansible.builtin.copy:
    src: "{{ ansible_hostname }}.cer"
    dest: "/certs/domain.crt"
    mode: 0644

- name: Copy Key Over
  ansible.builtin.copy:
    src: "{{ ansible_hostname }}.key"
    dest: "/certs/domain.key"
    mode: 0644

- name: Create Docker Registry
  community.docker.docker_container:
    name: registry
    image: registry:2
    restart: yes
    state: started
    volumes:
      - /certs:/certs
    env:
      REGISTRY_HTTP_ADDR: "0.0.0.0:443"
      REGISTRY_HTTP_TLS_CERTIFICATE: "/certs/domain.crt"
      REGISTRY_HTTP_TLS_KEY: "/certs/domain.key"
    ports:
      "443:443"