---
- name: Setup container registry host
  hosts: container_registry
  become: true
  tasks:
    - name: Install Docker
      ansible.builtin.import_role:
        name: homelab-containers

    - name: Create Container Registry
      ansible.builtin.import_role:
        name: homelab-container-registry

- name: Setup container hosts
  hosts: containers
  become: true
  tasks:
    - name: Install Docker
      ansible.builtin.import_role:
        name: homelab-containers
