---
- hosts: elastic
  become: yes
  tasks:
    - name: Install Docker
      ansible.builtin.import_role:
        name: homelab-containers

    - name: Setup Elasticsearch Node with Docker Compose
      ansible.builtin.import_role:
        name: homelab-elasticsearch-docker
