---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 7.15.0
  nodeSets:
  - name: default
    config:
      node.roles: ["master", "data"]
    podTemplate:
      metadata:
        labels:
          app: elasticsearch
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 4Gi
              cpu: 2
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms3g -Xmx3g"
    count: 3
    # volumeClaimTemplates:
    #   - metadata:
    #       name: elasticsearch-data
    #     spec:
    #       accessModes:
    #       - ReadWriteOnce
    #       storageClassName: standard
    #       resources:
    #         requests:
    #           storage: 8Gi
  http:
    service:
      spec:
        # expose this cluster Service with a LoadBalancer
        type: LoadBalancer
        # ports:
        # - name: http
        #   protocol: TCP
        #   port: 9200
        #   targetPort: 9200
 
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 7.15.0
  count: 1
  elasticsearchRef:
    name: "elasticsearch"
  http:
   service:
     spec:
       type: LoadBalancer
  podTemplate:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        resources:
          limits:
            memory: 1Gi
            cpu: 1