---
- name: Setting container_engine_type fact
  ansible.builtin.set_fact:
    container_engine_type: "docker"

- name: Install prerequisites for Docker
  ansible.builtin.dnf:
    name: ['device-mapper-persistent-data', 'lvm2', 'python3', 'amazon-linux-extras']

- name: Install Docker on Amazon Linux 2
  ansible.builtin.shell:
    cmd: amazon-linux-extras install docker -y
  changed_when: false

- name: Start Docker Service
  ansible.builtin.systemd:
    name: docker
    enabled: true
    daemon_reload: true
    state: started
  when: not ansible_check_mode
