---
- name: Setting container_engine_type fact
  set_fact: container_engine_type="docker"
  
- name: Install prerequisites for Docker and Cortex XSOAR
  ansible.builtin.yum:
    name: ['device-mapper-persistent-data', 'lvm2', 'python3', 'amazon-linux-extras']

- name: Install Docker on Amazon Linux 2
  shell: amazon-linux-extras install docker -y
  
- name: Start Docker Service
  ansible.builtin.systemd:
    name: docker
    enabled: yes
    daemon_reload: yes
    state: started
  when: not ansible_check_mode