---
- name: Setting container_engine_type fact
  ansible.builtin.set_fact:
    container_engine_type: "docker"

- name: Install prerequisites for Docker
  ansible.builtin.dnf:
    name: ['yum-utils', 'device-mapper-persistent-data', 'lvm2', 'python3']

- name: Add Docker repository
  ansible.builtin.shell:
    cmd: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo --enable
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker CE
  ansible.builtin.dnf:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']

- name: Start Docker Service
  ansible.builtin.systemd:
    name: docker
    enabled: true
    daemon_reload: true
    state: started
  when: not ansible_check_mode
