---
- name: Install prerequisites for Docker
  ansible.builtin.apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg2', 'software-properties-common', 'acl', 'python3-docker', 'python3']
    update_cache: yes

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present
    keyring: "/usr/share/keyrings/docker-archive-keyring.gpg"

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present

- name: Install Docker CE
  ansible.builtin.apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    update_cache: yes
  when: not ansible_check_mode

- name: Start Docker Service
  ansible.builtin.systemd:
    name: docker
    enabled: yes
    daemon_reload: yes
    state: started
  when: not ansible_check_mode