---
- name: Install packages
  ansible.builtin.yum:
    name: ['sudo','qemu-guest-agent','python3']

- name: Upgrade all packages
  ansible.builtin.yum:
    name: '*'
    state: latest

- name: Stop and disable firewalld
  ansible.builtin.systemd:
    name: firewalld
    enabled: no
    state: stopped

- name: Add very-last service
  ansible.builtin.copy:
    src: redhat-very-last.service.txt
    dest: /etc/systemd/system/very-last.service
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution == "RedHat"

- name: Add very-last shell script
  ansible.builtin.copy:
    src: redhat-very-last.sh
    dest: /usr/local/sbin/very-last
    owner: root
    group: root
    mode: 0700
  when: ansible_distribution == "RedHat"